export const AppConfig = {
  MasterEmails: ["dev@gramflow.pro"],
  AdminEmails: ["dev@gramflow.pro"],
  StoreName: "Gramflow Store",
  logo: "https://www.gramflow.pro/logo.svg",
  ReturnAddress: {
    house_number: "Mumbai Heights",
    locality: "Sector 224",
    city: "Mumbai",
    state: "Maharashta",
    pincode: "400024",
    country: "India",
    phone_no: "9999999999",
    name: "Gramflow Store",
  },
  DefaultPaymentMode: "prepaid",
  DefaultPackageDetails: {
    SMALL: {
      weight: "500",
      length: "20",
      breadth: "20",
      height: "5",
      charge: "50",
      color: "red",
      payment_mode: "prepaid",
    },
    MEDIUM: {
      weight: "500",
      length: "25",
      breadth: "20",
      color: "blue",
      height: "10",
      charge: "60",
      payment_mode: "prepaid",
    },
    LARGE: {
      weight: "1000",
      length: "28",
      charge: "100",
      color: "teal",
      breadth: "28",
      height: "13",
      payment_mode: "prepaid",
    },
    ["VERY LARGE"]: {
      weight: "1200",
      length: "32",
      charge: "150",
      color: "purple",
      breadth: "32",
      height: "16",
      payment_mode: "prepaid",
    },
  },
  WarehouseDetails: {
    house_number: "Mumbai Heights",
    locality: "Sector 224",
    city: "Mumbai",
    state: "Maharashta",
    pincode: "400024",
    country: "India",
    phone_no: "9999999999",
    name: "Gramflow Store",
    email: "dev@gramflow.pro",
  },
  OrderWebsiteDetails: {
    name: "Gramflow Orders",
    description: "Please fill in details about your order",
    url: "https://order.gramflow.pro",
  },
  AdminWebsiteDetails: {
    name: "Gramflow Admin",
    description: "Gramflow is a platform for clothing.",
    url: "https://admin.gramflow.pro",
  },
  InstagramUsername: "gramflow.pro",
  BaseAdminUrl: "https://admin.gramflow.pro",
  BaseOrderUrl: "https://order.gramflow.pro",
  ImageBaseUrl: "https://images.gramflow.pro",
  BaseStoreUrl: "https://gramflow.pro",
  Domain: "gramflow.pro",
};
